### ISSUE TITLE
chat audio recorder polishing

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#102]
Für die Audioaufnahme fehlt eine Zeitleiste. 
![D2478E04-7566-40EA-8C54-A29CC03651F8](https://user-images.githubusercontent.com/37026678/80360355-7eee6c00-887f-11ea-9989-bfb6c212b54f.jpeg)
![6BD78ABC-FF91-44EA-BFBA-09A13AAE6277](https://user-images.githubusercontent.com/37026678/80360358-801f9900-887f-11ea-82d4-f05ab5c6dbef.jpeg)
![10D8BE46-9028-488E-BBD7-63125825F529](https://user-images.githubusercontent.com/37026678/80360360-801f9900-887f-11ea-9e90-dc7230478f6d.jpeg)

**Comment by am-katrin** [comment]
@baumwehn was genau soll hier angezeigt werden ?

**Comment by baumwehn** [comment]
@am-katrin 

Das Audio kann abgespielt werden. Daher sollte eine Zeitleiste sowie eine Zeitangabe für die Aufnahme sichtbar sein. Aktuell werden nur die Buttons angezeigt

**Comment by baumwehn** [comment]
Als Beispiel der Audio Player auf Portalseite
![B48A1EEB-9910-421A-8803-FB0B83BA35F1](https://user-images.githubusercontent.com/37026678/80363520-9e3bc800-8884-11ea-85fd-f49985b55968.jpeg)
