### ISSUE TITLE
Autorenmodus

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#103]
Der Autorenmodus soll aktivierbar sein.

Zeiger auf das Live Portal.

Der Bereich in den Einstellungen soll nicht mehr ausgegraut sein.
![2B8B2FD2-C3C4-4EC1-920C-BB9BDF69A211](https://user-images.githubusercontent.com/37026678/80360613-e60c2080-887f-11ea-80bf-321a38feb119.png)

Die Kachel muss angepasst werden.
![06ECC2FA-EB27-4C64-B4EF-097B06FB967B](https://user-images.githubusercontent.com/37026678/80360653-f3c1a600-887f-11ea-8657-6778cd938c8e.png)

**Comment by am-katrin** [comment]
fixed in version 2.6.3
