### ISSUE TITLE
Authoring App. Caching des Portals

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#105]
wäre es möglich, den web view für das portal in der app zu cachen?

das wird aktuell beim wählen des tabs mit der default url initialisiert und auch jedes mal neu geladen, wenn man zwischendurch etwas anderes macht.

das initialisieren passt nach dem app start.

danach sollte einfach der letzte zustand wieder angezeigt werden

**Comment by am-katrin** [comment]
fixed in 2.6.11
