### ISSUE TITLE
Automatic assignment of task does not work anymore

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#106]
How to reproduce:
Inside the mcm webportal, create a digital classroom with the option activated "assign tasks automatically". From the app, join the created digital classroom.

What is wrong?
You can see all tasks on the map.

What behaviour is expected:
The user should only the task that has been assigned to him by the system. This information is stored in the session user inside the field "assigned_task_id"

**Comment by DaSchee** [comment]
Fix release in 2.6.11
