### ISSUE TITLE
Session Chat: Image rotation

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#108]
Wird ein Bild für den Chat aufgenommen soll es nicht gedreht werden.

**Comment by baumwehn** [comment]
Der Fehler tritt auf einem Galaxy S7 auf.

**Comment by baumwehn** [comment]
Der Fehler tritt auch auf einem Pixel 3 XL auf.

**Comment by am-katrin** [comment]
fixed in 2.6.12 (tested on samsung galaxy)
