### ISSUE TITLE
Session Chat: Extended Image functions

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#109]
Images should be clickable within chat history to maximize them.

The necessary effort for implementing a small image editor (rotate, cut to size) should be examined.

An example is the editor within the web portal (https://mathcitymap.eu/de/portal/#!/task/create) "choose picture"

**Comment by am-katrin** [comment]
Was umgesetzt wird nach absprache mit ML:
- große Darstellung von gesendeten Bildern (nach klick)

**Comment by am-katrin** [comment]
added function to show image in fullscreen after click. (v2.6.12)
