### ISSUE TITLE
New Trail Setting: Enable / Disable answer feedback

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#111]
Eine neue Trail-Einstellung soll für das Ablaufen eines Trails hinzugefügt werden:
- Überprüfung / bzw. Rückmeldung zu der Antworteingabe.

**Technische Informationen:** Intern wird die Einstellung für Trails im Feld "attr" unter dem Key "answerFeedback" gespeichert.

**Standardbelegung:** Bei Trails, die nicht diesen Key im attr Feld enthalten, soll die Einstellung standardmäßig aktiviert (true sein).

**Einstellung aktiviert:** App soll wie bisher dem User die Eingabe einer Antwort ermöglichen und diese Validieren und eine Rückmeldung via Dialog + Design einer Aufgabe geben. (sprich bisheriges Vorgehen bleibt erhalten).

**Einstellung deaktiviert:** Der User soll weiterhin die Möglichkeit haben, eine Antwort eintippen zu können (bzw. bei MC Optionen zu markieren). Allerdings soll ihm kein Feedback-Dialog (richtig oder falsch) angezeigt werden. Der Ablauf soll wie folgt modifiziert werden.

- Der Button soll von "Prüfen" zu "Speichern" umbenannt werden. 
- Weiterhin soll das Ergebnis intern dennoch validiert werden und im Rahmen eines digitalen Klassenzimmers auch weiterhin als Event an den Lehrer gesendet werden.
- Der App-User soll das eingetippte Ergebnis im Nachhinein überschreiben und neu speichern können

Testdaten:
- Zum Testen bitte dev.mathcityma.eu verwenden
- Trailcode: 391804

**Comment by am-katrin** [comment]
@iwanmcm folgende Fragen haben sich bei uns ergeben:

- Sollen die Hinweise / Musterlösung angezeigt werden ?
- Was ist mit einem Guided Trails ?
- Wie soll mit den Fehlversuchen verfahren werden ?
- Bekommt der Nutzer ein Feedback wenn er alle Aufgaben gelöst hat oder überhaupt keins ?
- Was soll in der Trail-Übersicht angezeigt werden (erfolgreich gelöst, übersprungen,... ) ?
- Was ist mit dem Score-Board im Digital Classroom ?
- Ist das Feature nur für den Digital Classroom ?

**Comment by iwanmcm** [comment]
- Sollen die Hinweise / Musterlösung angezeigt werden ? *Diese Funktionen sollen von der neuen Option unberührt bleiben, hierfür gibt es separate Einstellungen, die bereits implementiert sind*
- Was ist mit einem Guided Trails ? *Die Funktion soll von der neuen Option ebenfalls nicht geändert werden*
- Wie soll mit den Fehlversuchen verfahren werden ? *Die Eingabe soll beim Klicken auf den Button "Speichern" intern evaluiert werden. Fehlversuche sollen nicht mitgezählt werden, Im Falle eines digitalen Klassenzimmers soll aber weiterhin das dazugehörige Event gesendet werden*
- Bekommt der Nutzer ein Feedback wenn er alle Aufgaben gelöst hat oder überhaupt keins ? * Aufgaben, zu denen die Schüler eine Lösung eingetippt und "gespeichert" haben, sollen in der Farbe Lila kodiert werden. Der Zustand wird als "bearbeitet" bezeichnet. Wenn alle Aufgaben auf "bearbeitet" stehen soll folgende Meldung erscheinen: "Super, du hast alle Aufgaben bearbeitet." 
- Was soll in der Trail-Übersicht angezeigt werden (erfolgreich gelöst, übersprungen,... ) ? *Bearbeitet*
- Was ist mit dem Score-Board im Digital Classroom ? *Dies soll ausgeblendet werden*
- Ist das Feature nur für den Digital Classroom ? *Nein, die Einstellung bezieht sich auch auf einen normalen Trail*
