### ISSUE TITLE
MathJax display bug Multiple Choice

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#112]
The MathJax mathematical formulas are not correctly displayed on first open of the task for multiple choice tasks.
After clicking on check or on a hint, the formula is correctly displayed.

Expected behaviour: Correctly display mathjax formulas in multiple choice tasks also on first load.

Test data:
Trailcode: 063152
task; #1 Fahrrad

Tested on Android.

**Comment by DaSchee** [comment]
I couldn't reproduce this issue on my device (Android 8.1), do you have a consistent way to reproduce this issue or additional information about the device it has been encountered on?

**Comment by iwanmcm** [comment]
Google Pixel 3XL on Android 10:
![image](https://user-images.githubusercontent.com/30897901/94699144-4c6b0280-033a-11eb-94e5-2d3baa0677c0.png)

I will ask also my colleague to tell me her device.

**Comment by DaSchee** [comment]
I was able to reproduce this issue on a simulated Android 10 device and will look into it now.

**Comment by iwanmcm** [comment]
Galaxy A7 (2018)

One UI-Version 2.0

Android-Version 10

**Comment by iwanmcm** [comment]
Tested and works fine
