### ISSUE TITLE
Map tiles not displayed in trail tasks view

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#114]
This issue occurs right now on Android only. How to reproduce:

- Download any trail (e.g. Bockenheimtrail 9/10) => The download itselfs works as expected
- Start trail => Position and task locations are visible, but the map tiles are not (no streets etc.)

Please fix ASAP

**Comment by DaSchee** [comment]
Reviewed by @iwanmcm and Fix uploaded to play-store
