### ISSUE TITLE
Onboarding auf Englisch (App auf deutsch) Pixel3a Android 11

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#115]
![2](https://user-images.githubusercontent.com/37026678/98567114-db5f2900-22af-11eb-8365-746a7c287136.jpg)
![1](https://user-images.githubusercontent.com/37026678/98567123-dd28ec80-22af-11eb-84b5-94a22e722d83.jpg)

**Comment by DaSchee** [comment]
Fehler sollte im aktuellen Build nicht mehr auftreten. Bitte bestätigen und gegebenenfalls diese Ticket schließen.
