### ISSUE TITLE
Multiple Choice Answers not properly displayed

### ISSUE THREAD

**Issue by DXKOehler** [MathCityMap/O1-MCM-mobile-App#116]
As visible in the screenshot, it is currently not possible to solve multiple choice tasks with answers exceeding a certain text length.
We suggest allowing linebreaks here to not limit the answer length. Please find the respective task under: https://mathcitymap.eu/de/portal/#!/trail/453823/task/3419950
Since these tasks are not to solve, the issue is quite urgent. Thanks in advance.

![photo_2021-01-20_11-41-18](https://user-images.githubusercontent.com/50801867/105164450-73318c80-5b15-11eb-9eba-887aeede98aa.jpg)

**Comment by DaSchee** [comment]
Version 3.0.11 in Firebase enthält einen Fix
