### ISSUE TITLE
Map data lost

### ISSUE THREAD

**Issue by ulyanenkovs** [MathCityMap/O1-MCM-mobile-App#12]
After trying solving a task and afterwards returning to the map, the map is not visible anymore and scrolling causes even more strange behaviour
![screenshot_20180212-144353](https://user-images.githubusercontent.com/10231237/36099552-5e7d1058-1003-11e8-9145-dde8010f871a.png)

**Comment by iwanmcm** [comment]
@ulyanenkovs can you please test, if the problem still exists after fix?
