### ISSUE TITLE
GPS Tasks

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#16]
Implement GPS Task (solutionType: gps) functionality inside task detail view.

The user should see a map within the task detail view, where he is able to place markers based on his position to solve one of the given tasks.

The validation is processed within the app. In some cases against given points in the solution string, in other cases based on the set points.

The feedback in this case is more individual and based on placed markes.

Available gps tasks:
- walk a line of x meter (lineNoDirection)
- walk a line of x meter from South to North (lineDirection)
- walk a square with x meter side length (square)
- walk a equilateral triangle with x meter side length (triangle)
- find a point that has same distance to two given points (centerTwo) [Display 2 points in map]
- find a point that has same distance to three given points (centerThree) [Display 3 points in map]
- find positions for two points that define a given linear function (linearFx) [Display x- and y-axis in map]

**Comment by iwanmcm** [comment]
Android code for GPS tasks
`
public class GpsTask {
    static int BEARING_GREEN = 5;
    static int BEARING_ORANGE = 10;
    static int LENGTH_GREEN = 5;
    static int LENGTH_ORANGE = 10;
    static double SLOPE_GREEN = 0.3;
    static double SLOPE_ORANGE = 0.5;
    static int Y_GREEN = 3;
    static int Y_ORANGE = 8;
    static int AXIS_LENGTH = 100;
    static int MARK_DISTANCE = 10;
    static int MARK_LENGTH = 3;

    public static Feedback checkLine(GeoPoint a, GeoPoint b, int lengthWanted){
        int length = a.distanceTo(b);
        int lengthSolution = 0;

        // Lenge überprüfen
        if(length > (lengthWanted - LENGTH_GREEN) && length < (lengthWanted + LENGTH_GREEN)){
            lengthSolution = 2;
        }
        else if(length > (lengthWanted - LENGTH_ORANGE) && length < (lengthWanted + LENGTH_ORANGE)){
            lengthSolution = 1;
        }
        else{
            lengthSolution = 0;
        }

        Feedback feedback = new Feedback();
        if(lengthSolution == 2){
            // Beide im grünen Bereich
            feedback.solved = 2;
            feedback.score = 100;
        }
        else if(lengthSolution > 0){
            feedback.solved = 1;
            feedback.score = 50;
        }
        else{
            feedback.solved = 0;
            feedback.score = 0;
        }

        // Füge Werte als Rückmeldung hinzu
        feedback.details.put("length", String.valueOf(length));

        return feedback;
    }

    /*
    Überprüft ob eine Strecke (definiert durch die Punkte a und b) einer geforderten Länge und Ausrichtung entspricht
    @param GeoPoint a Startpunkt
    @param GeoPoint b Endpunkt
    @param int lengthWanted geforderte Länge
    @param int angleWanted geforderte Ausrichtung
    @return Feedback 
     */
    public static Feedback checkLineDirection(GeoPoint a, GeoPoint b, int lengthWanted, int angleWanted){
        int length = a.distanceTo(b);
        int lengthSolution = 0;
        double bearing = a.bearingTo(b);
        int bearingSolution = 0;

        // Grenze neu berechnen, wenn negativ (+360);; -5 wird zu 355
        boolean or = false;
        int leftGreen = angleWanted - GpsTask.BEARING_GREEN;
        int leftOrange = angleWanted - GpsTask.BEARING_ORANGE;
        if(leftGreen < 0){ leftGreen += 360; or = true;}
        if(leftOrange < 0){ leftOrange += 360; or = true;}
        if(!or){
            // Winkel überprüfen
            if(bearing > leftGreen && bearing < (angleWanted + BEARING_GREEN)){
                bearingSolution = 2;
            }
            else if(bearing > leftOrange && bearing < (angleWanted + BEARING_ORANGE)){
                bearingSolution = 1;
            }
            else{
                bearingSolution = 0;
            }
        }
        else{
            // Winkel überprüfen
            if(bearing > leftGreen || bearing < (angleWanted + BEARING_GREEN)){
                bearingSolution = 2;
            }
            else if(bearing > leftOrange || bearing < (angleWanted + BEARING_ORANGE)){
                bearingSolution = 1;
            }
            else{
                bearingSolution = 0;
            }
        }


        // Lenge überprüfen
        if(length > (lengthWanted - LENGTH_GREEN) && length < (lengthWanted + LENGTH_GREEN)){
            lengthSolution = 2;
        }
        else if(length > (lengthWanted - LENGTH_ORANGE) && length < (lengthWanted + LENGTH_ORANGE)){
            lengthSolution = 1;
        }
        else{
            lengthSolution = 0;
        }

        Feedback feedback = new Feedback();
        if(bearingSolution == 2 && lengthSolution == 2){
            // Beide im grünen Bereich
            feedback.solved = 2;
            feedback.score = 100;
        }
        else if(bearingSolution > 0 && lengthSolution > 0){
            feedback.solved = 1;
            feedback.score = 50;
        }
        else{
            feedback.solved = 0;
            feedback.score = 0;
        }

        // Füge Werte als Rückmeldung hinzu
        feedback.details.put("length", String.valueOf(length));
        feedback.details.put("bearing", String.valueOf(Math.round(bearing)));

        return feedback;
    }

    public static Feedback checkTriangle(GeoPoint a, GeoPoint b, GeoPoint c, int lengthWanted){
        int[] edgesLength = new int[]{a.distanceTo(b), b.distanceTo(c), c.distanceTo(a)};
        boolean allGreen = true;
        boolean allOrange = true;

        // Überprüfe Länge der Kanten
        for(int i = 0; i < edgesLength.length; i++){
            int l = edgesLength[i];
            if(l > lengthWanted - GpsTask.LENGTH_GREEN && l < lengthWanted + GpsTask.LENGTH_GREEN){
            }
            else if(l > lengthWanted - GpsTask.LENGTH_ORANGE && l < lengthWanted + GpsTask.LENGTH_ORANGE){
                allGreen = false;
            }
            else{
                allGreen = false;
                allOrange = false;
            }
        }

        Feedback feedback = new Feedback();

        if(allGreen){
            feedback.solved = 2;
            feedback.score = 100;
        }
        else if(allOrange){
            feedback.solved = 1;
            feedback.score = 75;
        }
        else{
            feedback.solved = 0;
            feedback.score = 0;
        }

        feedback.details.put("a", String.valueOf(edgesLength[0]));
        feedback.details.put("b", String.valueOf(edgesLength[1]));
        feedback.details.put("c", String.valueOf(edgesLength[2]));

        return feedback;
    }

    public static Feedback checkSquare(GeoPoint a, GeoPoint b, GeoPoint c, GeoPoint d, int lengthWanted){
        int[] edgesLength = new int[]{a.distanceTo(b), b.distanceTo(c), c.distanceTo(d), d.distanceTo(a)};
        int[] lengthSolutions = new int[]{0,0,0,0};
        int diagonalSolution = 0;
        boolean allGreen = true;
        boolean allOrange = true;

        // Überprüfe Länge der Kanten
        for(int i = 0; i < edgesLength.length; i++){
            int l = edgesLength[i];
            if(l > lengthWanted - GpsTask.LENGTH_GREEN && l < lengthWanted + GpsTask.LENGTH_GREEN){
                lengthSolutions[i] = 2;
            }
            else if(l > lengthWanted - GpsTask.LENGTH_ORANGE && l < lengthWanted + GpsTask.LENGTH_ORANGE){
                lengthSolutions[i] = 1;
                allGreen = false;
            }
            else{
                lengthSolutions[i] = 0;
                allOrange = false;
                allGreen = false;
            }
        }

        // Überprüfe Diagonalen auf gleiche Länge
        int diagonale1 = a.distanceTo(c);
        int diagonale2 = b.distanceTo(d);

        if(Math.abs(diagonale1 - diagonale2) < GpsTask.LENGTH_GREEN){
            diagonalSolution = 2;
        }
        else if(Math.abs(diagonale1 - diagonale2) < GpsTask.LENGTH_ORANGE){
            diagonalSolution = 1;
        }
        else {
            diagonalSolution = 0;
        }

        Feedback feedback = new Feedback();

        if(allGreen && diagonalSolution == 2){
            feedback.solved = 2;
            feedback.score = 100;
        }
        else if(allOrange && diagonalSolution > 0){
            feedback.solved = 1;
            feedback.score = 75;
        }
        else{
            feedback.solved = 0;
            feedback.score = 0;
        }

        feedback.details.put("AB", String.valueOf(edgesLength[0]));
        feedback.details.put("BC", String.valueOf(edgesLength[1]));
        feedback.details.put("CD", String.valueOf(edgesLength[2]));
        feedback.details.put("DA", String.valueOf(edgesLength[3]));
        feedback.details.put("AC", String.valueOf(diagonale1));
        feedback.details.put("BD", String.valueOf(diagonale2));

        return feedback;
    }

    public static Feedback checkCenterTwoPoints(GeoPoint givenA, GeoPoint givenB, GeoPoint pos){
        int distanceA = pos.distanceTo(givenA);
        int distanceB = pos.distanceTo(givenB);
        int delta = Math.abs(distanceA - distanceB);
        int solution;

        if(delta < GpsTask.LENGTH_GREEN){
            solution = 2;
        }
        else if(delta < GpsTask.LENGTH_ORANGE){
            solution = 1;
        }
        else {
            solution = 0;
        }

        Feedback feedback = new Feedback();
        feedback.solved = solution;
        if(solution == 2){
            feedback.score = 100;
        }
        else if(solution == 1){
            feedback.score = 75;
        }
        else{
            feedback.score = 0;
        }
        feedback.details.put("delta", String.valueOf(delta));
        return feedback;
    }

    public static Feedback checkCenterThreePoints(GeoPoint givenA, GeoPoint givenB, GeoPoint givenC, GeoPoint pos){
        int distanceA = pos.distanceTo(givenA);
        int distanceB = pos.distanceTo(givenB);
        int distanceC = pos.distanceTo(givenC);
        int deltaAB = Math.abs(distanceA - distanceB);
        int deltaBC = Math.abs(distanceB - distanceC);
        int solution = 0;

        if(deltaBC < GpsTask.LENGTH_GREEN && deltaAB < GpsTask.LENGTH_GREEN){
            solution = 2;
        }
        else if(deltaBC < GpsTask.LENGTH_ORANGE && deltaAB < GpsTask.LENGTH_ORANGE){
            solution = 1;
        }
        else {
            solution = 0;
        }

        Feedback feedback = new Feedback();
        feedback.solved = solution;
        if(solution == 2){
            feedback.score = 100;
        }
        else if(solution == 1){
            feedback.score = 75;
        }
        else{
            feedback.score = 0;
        }
        feedback.details.put("deltaAB", String.valueOf(deltaAB));
        feedback.details.put("deltaBC", String.valueOf(deltaBC));
        return feedback;
    }

    public static Feedback checkLinearFx(GeoPoint c0, GeoPoint c1, GeoPoint a, GeoPoint b, double slope, int yValue){
        if(c0.distanceTo(c1) < AXIS_LENGTH){
            c1 = c0.destinationPoint(AXIS_LENGTH, (float) c0.bearingTo(c1));
        }

        // Berechne y-Achsen-Punkt
        float yAngle = (float) c0.bearingTo(c1) - 90;
        if(yAngle < 0){
            yAngle += 360;
        }
        GeoPoint y = c0.destinationPoint(AXIS_LENGTH, yAngle);

        // Überprüfe, ob A näher an y-Achse ist als b, falls nicht tausche Punkte
        double aX = getDistanceToLine(a, c0, y);
        double bX = getDistanceToLine(b, c0, y);
        if(aX > bX){
            // Tausche A und B für Überprüfung
            GeoPoint helperPoint = a;
            a = b;
            b = helperPoint;
        }
        // / Distanz der Punkte von der x-Achse
        double aY = getDistanceToLine(a, c0, c1);
        double bY = getDistanceToLine(b, c0, c1);
        // Höhendifferenz der Punkte  A und B, abhängig von der Lage der Koordinatenachse (BY - AY).
        double deltaY = bY - aY;
        // Längendifferenz über Satz des Pythagoras
        double deltaX = bX - aX;
        // Steigung deltaY / deltaX
        double m = deltaY / deltaX;

        // Y-Achsenabschnitt berechnen: Funktionswert von a (=aX) - Steigung (m) * x-Wert (aY)
        int yInMeters = (int) (aY - m * aX);

        // Validieren
        int solutionSlope = 0;
        int solutionY = 0;
        if(m > slope - SLOPE_GREEN && m < slope + SLOPE_GREEN){
            solutionSlope = 2;
        }
        else if(m > slope - SLOPE_ORANGE && m < slope + SLOPE_ORANGE){
            solutionSlope = 1;
        }

        if(yInMeters > yValue - Y_GREEN && yInMeters < yValue + Y_GREEN){
            solutionY = 2;
        }
        else if(yInMeters > yValue - Y_ORANGE && yInMeters < yValue + Y_ORANGE){
            solutionY = 1;
        }

        Feedback feedback = new Feedback();
        if(solutionSlope == 2 && solutionY == 2){
            feedback.solved = 2;
            feedback.score = 100;
        }
        else if(solutionSlope > 0 && solutionY > 0){
            feedback.solved = 1;
            feedback.score = 75;
        }
        else{
            feedback.solved = 0;
            feedback.score = 0;
        }

        feedback.details.put("slope", String.valueOf((double) Math.round(m * 10d) / 10d));
        String yVal = "";
        if(yInMeters >= 0){
            yVal = " + " + String.valueOf(Math.abs(yInMeters));
        }
        else{
            yVal = " - " + String.valueOf(Math.abs(yInMeters));
        }
        feedback.details.put("y", yVal);

        return feedback;
    }

    /*
    Zeichnet ein Koordinatensystem mit Beschriftung und den Maßen 100m x 100m
    @param MapView mapView
    Karte auf die gezeichnet werden soll
    @param GeoPoint zero
    Nullpunkt der Koordinatenachse
    @param xEnd
    Endpunkt der x-Achse (legt Richtung fest). Falls Distanz von zero nach xEnd kleiner als 100 meter ist,
    so wird x-end verschoben auf 100 m
     */
    public static void drawAxis(MapView mapView, GeoPoint zero, GeoPoint xEnd){
        int axisColor = Color.RED;
        int axisWidth = 5;
        int arrowDegree = 150;
        int arrowLength = 7;
        int axisTitleDistance = 5;
        int textSize = 45;
        int textSizeDis = 30;

        // Draw 100m x 100m Axis in Red
        if(zero.distanceTo(xEnd) < AXIS_LENGTH){
            xEnd = zero.destinationPoint(AXIS_LENGTH, (float)zero.bearingTo(xEnd));
        }
        float yAngle = (float) zero.bearingTo(xEnd) - 90;
        if(yAngle < 0){
            yAngle += 360;
        }
        List<GeoPoint> axis = new ArrayList<>();
        axis.add(xEnd); // x-Achse Endepunkt
        axis.add(zero); // x-y-Achse (0-Punkt)
        axis.add(axis.get(1).destinationPoint(AXIS_LENGTH, yAngle)); // y-Achse 0 Punkt - Suche Punkt der sich im rechten Winkel 100m vom 0-Punkt entfernt befindet

        // Draw little arrows on end of axis
        List<GeoPoint> arrowX = new ArrayList<>();
        List<GeoPoint> arrowY = new ArrayList<>();
        arrowX.add(xEnd.destinationPoint(arrowLength, (float) zero.bearingTo(xEnd) - arrowDegree));
        arrowX.add(xEnd);
        arrowX.add(xEnd.destinationPoint(arrowLength, (float) zero.bearingTo(xEnd) + arrowDegree));
        GeoPoint yEnd = axis.get(2);
        arrowY.add(yEnd.destinationPoint(arrowLength, (float) zero.bearingTo(yEnd) - arrowDegree));
        arrowY.add(yEnd);
        arrowY.add(yEnd.destinationPoint(arrowLength, (float) zero.bearingTo(yEnd) + arrowDegree));

        // Draw lines
        List<List<GeoPoint>> lines = new ArrayList<>();
        lines.add(axis);
        lines.add(arrowX);
        lines.add(arrowY);

        // Zeichne alle 10 Meter kleine Markierungen / Insgesamt aber nur 9 Stück
        for(int i = 1; i < 10; i++){
            List<GeoPoint> markX = new ArrayList<>();
            List<GeoPoint> markY = new ArrayList<>();

            // x-Achse
            GeoPoint onX = zero.destinationPoint(i * MARK_DISTANCE, (float) zero.bearingTo(xEnd));
            GeoPoint endMarkX = onX.destinationPoint(MARK_LENGTH, yAngle);
            markX.add(onX);
            markX.add(endMarkX);

            // y-Achse
            GeoPoint onY = zero.destinationPoint(i * MARK_DISTANCE, yAngle);
            GeoPoint endMarkY = onY.destinationPoint(MARK_LENGTH, (float) zero.bearingTo(xEnd));
            markY.add(onY);
            markY.add(endMarkY);

            // add to lines
            lines.add(markX);
            lines.add(markY);
        }

        for(List<GeoPoint> points : lines){
            Polyline line = new Polyline();
            line.setPoints(points);
            line.setColor(axisColor);
            line.setWidth(axisWidth);
            mapView.getOverlays().add(line);
        }

        // Add Text "x" and "y" to axis
        // X
        Marker textX = new Marker(mapView);
        textX.setTitle("x");
        textX.setIcon(new BitmapDrawable(mapView.getContext().getResources(), textAsBitmap("x", textSize, axisColor)));
        textX.setPosition(xEnd.destinationPoint(axisTitleDistance, (float)zero.bearingTo(xEnd)));
        textX.setInfoWindow(null);
        mapView.getOverlays().add(textX);

        // Y
        Marker textY = new Marker(mapView);
        textY.setTitle("y");
        textY.setIcon(new BitmapDrawable(mapView.getContext().getResources(), textAsBitmap("y", textSize, axisColor)));
        textY.setPosition(yEnd.destinationPoint(axisTitleDistance + 3, (float)zero.bearingTo(yEnd)));
        textY.setInfoWindow(null);
        mapView.getOverlays().add(textY);

        // 50m X
        Marker disX50 = new Marker(mapView);
        disX50.setTitle("50m");
        disX50.setIcon(new BitmapDrawable(mapView.getContext().getResources(), textAsBitmap("50m", textSizeDis, axisColor)));
        disX50.setPosition(zero.destinationPoint(50, (float)zero.bearingTo(xEnd)).destinationPoint(7, (float) yEnd.bearingTo(zero)));
        disX50.setInfoWindow(null);
        mapView.getOverlays().add(disX50);

        // 100m X
        Marker disX = new Marker(mapView);
        disX.setTitle("100m");
        disX.setIcon(new BitmapDrawable(mapView.getContext().getResources(), textAsBitmap("100m", textSizeDis, axisColor)));
        disX.setPosition(xEnd.destinationPoint(axisTitleDistance + 3, (float)zero.bearingTo(xEnd) + 90));
        disX.setInfoWindow(null);
        mapView.getOverlays().add(disX);

        // 50m Y
        Marker disY50 = new Marker(mapView);
        disY50.setTitle("50m");
        disY50.setIcon(new BitmapDrawable(mapView.getContext().getResources(), textAsBitmap("50m", textSizeDis, axisColor)));
        disY50.setPosition(zero.destinationPoint(50, (float)zero.bearingTo(yEnd)).destinationPoint(7, (float) xEnd.bearingTo(zero)));
        disY50.setInfoWindow(null);
        mapView.getOverlays().add(disY50);
        
        // 100m Y
        Marker disY = new Marker(mapView);
        disY.setTitle("100m");
        disY.setIcon(new BitmapDrawable(mapView.getContext().getResources(), textAsBitmap("100m", textSizeDis, axisColor)));
        disY.setPosition(yEnd.destinationPoint(axisTitleDistance + 6, (float)zero.bearingTo(yEnd) - 90));
        disY.setInfoWindow(null);
        mapView.getOverlays().add(disY);

        // 0
        Marker dis0 = new Marker(mapView);
        dis0.setTitle("0");
        dis0.setIcon(new BitmapDrawable(mapView.getContext().getResources(), textAsBitmap("0", textSizeDis, axisColor)));
        dis0.setPosition(zero.destinationPoint(axisTitleDistance + 3, (float)yEnd.bearingTo(zero)));
        dis0.setInfoWindow(null);
        mapView.getOverlays().add(dis0);
    }

    /*
    Zeichnet einen text als Bitmap. Dies wird benutzt, um den Text auf die Karte zu bringen,
    in Form eines Icons von einem Marker
     */
    public static Bitmap textAsBitmap(String text, float textSize, int textColor) {
        Paint paint = new Paint(ANTI_ALIAS_FLAG);
        paint.setTextSize(textSize);
        paint.setColor(textColor);
        paint.setTextAlign(Paint.Align.LEFT);
        float baseline = -paint.ascent(); // ascent() is negative
        int width = (int) (paint.measureText(text) + 0.5f); // round
        int height = (int) (baseline + paint.descent() + 0.5f);
        Bitmap image = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(image);
        canvas.drawText(text, 0, baseline, paint);
        return image;
    }

    public static boolean isGeoPointInAxisBox(GeoPoint c0, GeoPoint c1, GeoPoint curPos){
        // Erweitere Koordinaten x-achse auf 100 Meter
        if(c0.distanceTo(c1) < AXIS_LENGTH){
            c1 = c0.destinationPoint(AXIS_LENGTH, (float) c0.bearingTo(c1));
        }

        float yAngle = (float) c0.bearingTo(c1) - 90;

        if(yAngle < 0){
            yAngle += 360;
        }

        GeoPoint y1 = c0.destinationPoint(AXIS_LENGTH, yAngle);
        GeoPoint cy = c1.destinationPoint(AXIS_LENGTH, yAngle);

        // Länge der x-Achse
        int x_axis_length = c0.distanceTo(c1);

        // Überprüfe, ob Punkt innerhalb des ersten Quadranten liegt
        // Entfernung von allen vier Seiten muss kleiner als jeweilige Achsenlänge sein)
        return getDistanceToLine(curPos, c0, c1) <= AXIS_LENGTH &&
                getDistanceToLine(curPos, y1, cy)  <= AXIS_LENGTH &&
                getDistanceToLine(curPos, c0, y1)  <= x_axis_length &&
                getDistanceToLine(curPos, c1, cy)  <= x_axis_length;
    }

    public static GeoPoint getNearestPoint(final GeoPoint p, final GeoPoint start, final GeoPoint end){
        if (start.equals(end)) {
            return start;
        }

        final double s0lat = Math.toRadians(p.getLatitude());
        final double s0lng = Math.toRadians(p.getLongitude());
        final double s1lat = Math.toRadians(start.getLatitude());
        final double s1lng = Math.toRadians(start.getLongitude());
        final double s2lat = Math.toRadians(end.getLatitude());
        final double s2lng = Math.toRadians(end.getLongitude());

        double s2s1lat = s2lat - s1lat;
        double s2s1lng = s2lng - s1lng;
        final double u = ((s0lat - s1lat) * s2s1lat + (s0lng - s1lng) * s2s1lng)
                / (s2s1lat * s2s1lat + s2s1lng * s2s1lng);
        if (u <= 0) {
            return start;
        }
        if (u >= 1) {
            return end;
        }

        return new GeoPoint(start.getLatitude() + (u * (end.getLatitude() - start.getLatitude())),
                start.getLongitude() + (u * (end.getLongitude() - start.getLongitude())));
    }

    public static int getDistanceToLine(final GeoPoint p, final GeoPoint start, final GeoPoint end){
        GeoPoint nearestPoint = getNearestPoint(p, start, end);
        return p.distanceTo(nearestPoint);
    }
}`

**Comment by am-immanuel** [comment]
Done.
