### ISSUE TITLE
Parse "New Lines" from textareas into HTML structure

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#25]
For structuring longer texts, users can create new lines (or break the row) within the web portal by pressing "enter"-key inside textarea. These new lines should be also reflected within the HTML structure of the app.

CSS-Solution:
Add style attribute:
white-space: pre-line

Taken from second answer of:
https://stackoverflow.com/questions/14948223/how-to-convert-n-to-html-line-break

**Comment by am-immanuel** [comment]
Done.
