### ISSUE TITLE
Change Start View of App to ListView till 30.04!

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#26]
DUE DATE: 30.04

Today we have discussed that it would make more sense, if the app would start in list view mode.

Please switch the tabs map <> list to "List | Map" and let the app start in list mode, so that it is not necessary for the map to load and use map data.

Also, this new arrangement is better if no internet connection is available, since the list works also in offline mode.

**Comment by Mrstolen** [comment]
App now starts with the List.
Tabs show [List | Map] instead of [Map | List]

I haven't test it much with mobile devices and on/offline, will do that next, but the changes are already pushed.

**Comment by am-immanuel** [comment]
Done.
