### ISSUE TITLE
Enhancement: Improve accessibility of app

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#39]
It was suggested to increase accessibility by adding the option to:

- Increase text size (for people who cannot see well)
- Automatically read text with voice over (for blind people)

**Comment by ChristianMercat** [comment]
Dear MCM fabulous team,

	A warm hello from Colombia with a first trail. I was beaten by a little easy cheesy bug: if the title contains a prime ‘ like in French in « l’abri », then the task can not be added to the trail, javascript protests.

	Updates tomorrow, best regards, Christian
