### ISSUE TITLE
Session Issues

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#40]
The following list shows some issues with the session feature. The list is not ordered by priority or something, but just to enumerate the issues. All issues need a fix.

Chat:

1. No notifcation when new messages arrive
2. Message ordering may become incorrect, when someone writes a message and sends it before the update tick delivers new messages that might have been written by the chat partner before.
3. Chat-history automatically scrolls down to messages that were just received. In some cases users might want to read received information and scroll up for this purpose. The chat-history window should auto-scroll only when user is at the bottom of chat. (Possible Solution in answer 4: https://stackoverflow.com/questions/18614301/keep-overflow-div-scrolled-to-bottom-unless-user-scrolls-up, I used it in the web portal).

General:

1. When restarting the trail no more information is shown (e.g. time left) that I am still part of session. An alert could solve this by shortly inform that the session will now continue.
2. Display Leaderboard information (Send score updates or event updates and send request to get updates of others score)
3. As soon as the user is part of a session, all other trails (that do not have any session) show also the chat and the leave session button. But they should not. They should show the usual buttons.

.

**Comment by am-immanuel** [comment]
Everything except the leaderboard information is implemented. I'll close this issue and create a specific one for the leaderboard information.
