### ISSUE TITLE
Trail outdated warning?

### ISSUE THREAD

**Issue by ChristianMercat** [MathCityMap/O1-MCM-mobile-App#41]
I don't quite like the sign for a downloaded trail, this "no entry sign" is misleading in my opinion (and some of the users I witnessed discussing it).
But I had problems with out dated trails. Could you please, when you happen to have an internet connection while using the app, check for the last version of the downloaded trails so that you could check whether or not the downloaded trail is up to date or not and then warn the user.

Thanks!

**Comment by am-immanuel** [comment]
On a fresh launch, the app now automatically updates the trails if there is a decent internet connection available.
I close this issue and created a distinct issue for creating a new icon for "trail is downloaded" (actually it was meant to mean: remove downloaded trail): #47
