### ISSUE TITLE
[Narrative in Session]: Leaderboard in new Desing takes too much space.

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#76]
The leaderboard takes too much space away (see screenshot). Make it a little bit smaller.

**Comment by iwanmcm** [comment]
![IMG_3199](https://user-images.githubusercontent.com/30897901/64420502-b6fe3000-d09f-11e9-9a18-208c03fba0c8.PNG)

At least this is the case for smaller devices

**Comment by ulyanenkovs** [comment]
Space saving is done.
