### ISSUE TITLE
Missing Icons in GPS tasks

### ISSUE THREAD

**Issue by iwanmcm** [MathCityMap/O1-MCM-mobile-App#84]
It seems that there are some markers missing for gps-tasks while using the narrative.

**Comment by iwanmcm** [comment]
![image](https://user-images.githubusercontent.com/30897901/65890905-f9b3df00-e3a3-11e9-8d24-6e144e0b5387.png)

**Comment by iwanmcm** [comment]
Just recently we received a user e-mail that was about missing markers in the GPS tasks with turned on narratives.
Please fix this issue soon.

Original message (german):
Letztes Wochenende beim BarCamp #bcEF19 Erfurt habe ich mit Teilnehmern die "Erzählung" PIRAT  getestet.   cool gemacht!!!
Nur beim Aufgabentyp GPS gab es allerdings das Problem, dass der Standort bzw. die Punkte auf der Karte nicht sichtbar waren (auf keinem Handy)!???
Im "normalem Modus" hat es funktioniert.

**Comment by ulyanenkovs** [comment]
Fixed and included to next big release "navigation v2"
