### ISSUE TITLE
Display Guided Trail Dialog after resetting trail.

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#89]
The user should be asked, if he/she likes to choose a starting task after resetting the trail.

**Comment by am-katrin** [comment]
fixed in version 2.6.3

**Comment by baumwehn** [comment]
Soll: Nach dem Zurücksetzen erscheint die Frage nach einem geführten Trail.

Ist: Nach dem Zurücksetzen erscheint die Frage nicht. Nachdem eine Aufgabe geöffnet oder geschlossen wurde (schließen/überspringen) erscheint die Frage nach einem geführten Trail.

**Comment by DaSchee** [comment]
fixed in version 2.6.13

**Comment by baumwehn** [comment]
@DaSchee 
Wenn ich nur eine Aufgabe überspringe, funktioniert das Zurücksetzen nicht. Erst wenn man eine andere Aufgabe geöffnet und wieder geschlossen hat, wird der Trail zurückgesetzt.

**Comment by DaSchee** [comment]
@baumwehn Der aktuellste Fehler ist in version 2.6.14 behoben
