### ISSUE TITLE
Restart/Delete Trail does not reset "guided trail"

### ISSUE THREAD

**Issue by baumwehn** [MathCityMap/O1-MCM-mobile-App#98]
Wenn eine Route zurückgesetzt wird, erscheint nicht die Frage, ob man eine Startaufgabe wählen möchte.

Wenn man einen "geführten Trail" löscht und neu runter läd, wird dieser nicht ganz zurück gesetzt. Die Aufgaben sind zwar zurück gesetzt, aber wenn vorher man eine Startaufgabe gewählt hat, sind nur die Aufgabenpins sichtbar, die man vor dem Löschen auch sehen konnte (der alte Fortschritt des guides Trail ist erhalten)

**Comment by DaSchee** [comment]
Ich habe soeben Testversion 2.6.4 released in der das Problem behoben ist.

**Comment by baumwehn** [comment]
Der Trail wird beim Löschen korrekt zurückgesetzt.

Das Zurücksetzen eines geöffneten Trails triggert aber den Modal für den guided trail noch nicht.

**Comment by am-katrin** [comment]
fixed in version 2.6.3

**Comment by baumwehn** [comment]
Fehler aus 106 wird durch diesen Fix verursacht. Bitte nochmal drauf schauen.

Das Zurücksetzen führt dazu, dass die absichtlich ausgeblendeten pins wieder eingeblendet werden.

Zudem erscheint die Frage nach einen geführten Trail wenn man die 1. Aufgabe öffnet und wieder schließt (oder löst und weiter klickt)

**Comment by DaSchee** [comment]
Behoben in 2.6.11
